[package]
name = "closure_cacher"
description = "Allows caching of user specified closure."
version = "0.1.1"
authors = ["Mohammed Khalil Ait Brahim <mohammed.khalil.ab@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
